name: my first CI/CD pipeline
on:
    push:
        branches:
            - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello from your CI/CD pipeline!"
